apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xgaidqyld-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xgaidqyld-java-quarkus-gitops